import { Coupon } from "../models/coupon.model";
import { Category } from "../models/category.model";
import { Product } from "../models/product.model";

const sampleCategories = [
  {
    name: "Gold Collection",
    slug: "gold",
    description: "Classic gold jewellery for everyday and occasion wear.",
    imageUrl: "/images/collection-gold.png",
  },
  {
    name: "Diamond Collection",
    slug: "diamond",
    description: "Diamond pieces with clean settings and bright sparkle.",
    imageUrl: "/images/collection-diamond.png",
  },
  {
    name: "Silver Collection",
    slug: "silver",
    description: "Polished silver designs with a modern lightweight feel.",
    imageUrl: "/images/collection-silver.png",
  },
  {
    name: "Bridal Collection",
    slug: "bridal",
    description: "Statement jewellery made for wedding and festive looks.",
    imageUrl: "/images/collection-bridal.png",
  },
];

const sampleProducts = [
  {
    sku: "GOLD-RING-001",
    name: "Aurelia Gold Ring",
    categorySlug: "gold",
    price: 42999,
    salePrice: 38999,
    images: ["/images/gold-ring.png"],
    tags: ["ring", "gold", "featured"],
    material: "Gold",
    goldPurity: "22K",
    weight: 6.2,
    makingCharges: 3200,
    hallmark: "BIS Hallmarked",
    stockCount: 12,
    shortDescription: "22K gold ring with a refined everyday profile.",
    description: "A polished 22K gold ring designed for daily wear and gifting.",
    isFeatured: true,
    isNewArrival: true,
    isBestSeller: true,
    isTrending: true,
    variants: [
      { size: "12", weight: 6.1, color: "Yellow Gold" },
      { size: "14", weight: 6.4, color: "Yellow Gold" },
    ],
  },
  {
    sku: "DIAMOND-EARRINGS-001",
    name: "Celeste Diamond Earrings",
    categorySlug: "diamond",
    price: 56999,
    salePrice: 52999,
    images: ["/images/diamond-earrings.png"],
    tags: ["earrings", "diamond", "new"],
    material: "Gold",
    goldPurity: "18K",
    weight: 4.8,
    stoneType: "Diamond",
    diamondDetails: "0.42 ct total diamond weight",
    makingCharges: 4500,
    hallmark: "BIS Hallmarked",
    stockCount: 8,
    shortDescription: "Diamond earrings with a bright, minimal setting.",
    description: "18K gold diamond earrings made for occasion looks and daily shine.",
    isFeatured: true,
    isNewArrival: true,
    isBestSeller: false,
    isTrending: true,
  },
  {
    sku: "SILVER-BANGLE-001",
    name: "Mira Silver Bangle",
    categorySlug: "silver",
    price: 8999,
    salePrice: 7499,
    images: ["/images/collection-silver.png"],
    tags: ["bangle", "silver"],
    material: "Silver",
    weight: 18.5,
    stockCount: 20,
    shortDescription: "Lightweight silver bangle with a polished finish.",
    description: "A clean silver bangle that stacks well or stands alone.",
    isFeatured: false,
    isNewArrival: true,
    isBestSeller: true,
    isTrending: false,
  },
  {
    sku: "BRIDAL-SET-001",
    name: "Ruhani Bridal Set",
    categorySlug: "bridal",
    price: 129999,
    salePrice: 119999,
    images: ["/images/bridal-banner.png"],
    tags: ["bridal", "set", "featured"],
    material: "Gold",
    goldPurity: "22K",
    weight: 32,
    stoneType: "Kundan",
    makingCharges: 12500,
    hallmark: "BIS Hallmarked",
    stockCount: 5,
    shortDescription: "A statement bridal set for wedding celebrations.",
    description: "A detailed bridal jewellery set with a rich festive presence.",
    isFeatured: true,
    isNewArrival: false,
    isBestSeller: true,
    isTrending: true,
  },
  {
    sku: "GOLD-CHAIN-001",
    name: "Saanvi Gold Chain",
    categorySlug: "gold",
    price: 68999,
    salePrice: 64999,
    images: ["/images/collection-gold.png"],
    tags: ["chain", "gold", "daily-wear"],
    material: "Gold",
    goldPurity: "22K",
    weight: 10.8,
    makingCharges: 5200,
    hallmark: "BIS Hallmarked",
    stockCount: 9,
    shortDescription: "A refined 22K gold chain for everyday styling.",
    description: "A versatile yellow gold chain with a clean link profile and secure clasp.",
    isFeatured: true,
    isNewArrival: false,
    isBestSeller: true,
    isTrending: false,
  },
  {
    sku: "GOLD-BANGLE-001",
    name: "Ira Gold Kada Bangle",
    categorySlug: "gold",
    price: 84999,
    salePrice: null,
    images: ["/images/gold-ring.png", "/images/collection-gold.png"],
    tags: ["bangle", "kada", "gold"],
    material: "Gold",
    goldPurity: "22K",
    weight: 14.6,
    makingCharges: 6800,
    hallmark: "BIS Hallmarked",
    stockCount: 7,
    shortDescription: "Traditional 22K gold kada with a polished finish.",
    description: "A bold yet wearable gold kada bangle made for festive and daily looks.",
    isFeatured: false,
    isNewArrival: true,
    isBestSeller: true,
    isTrending: true,
    variants: [
      { size: "2.4", weight: 14.2, color: "Yellow Gold" },
      { size: "2.6", weight: 14.9, color: "Yellow Gold" },
    ],
  },
  {
    sku: "GOLD-PENDANT-001",
    name: "Nysa Gold Pendant",
    categorySlug: "gold",
    price: 27999,
    salePrice: 24999,
    images: ["/images/collection-gold.png"],
    tags: ["pendant", "gold", "gift"],
    material: "Gold",
    goldPurity: "18K",
    weight: 3.9,
    makingCharges: 2400,
    hallmark: "BIS Hallmarked",
    stockCount: 15,
    shortDescription: "Minimal 18K gold pendant with soft curves.",
    description: "A lightweight pendant suited for gifting and everyday wear.",
    isFeatured: false,
    isNewArrival: true,
    isBestSeller: false,
    isTrending: true,
  },
  {
    sku: "DIAMOND-RING-001",
    name: "Elara Diamond Ring",
    categorySlug: "diamond",
    price: 74999,
    salePrice: 69999,
    images: ["/images/diamond-earrings.png", "/images/gold-ring.png"],
    tags: ["ring", "diamond", "engagement"],
    material: "Gold",
    goldPurity: "18K",
    weight: 5.1,
    stoneType: "Diamond",
    diamondDetails: "0.55 ct total diamond weight",
    makingCharges: 5800,
    hallmark: "BIS Hallmarked",
    stockCount: 6,
    shortDescription: "An elegant diamond ring with a luminous center setting.",
    description: "A graceful diamond ring crafted in 18K gold with fine accent stones.",
    isFeatured: true,
    isNewArrival: true,
    isBestSeller: true,
    isTrending: true,
    variants: [
      { size: "11", weight: 5, color: "Rose Gold" },
      { size: "13", weight: 5.2, color: "White Gold" },
    ],
  },
  {
    sku: "DIAMOND-PENDANT-001",
    name: "Veda Diamond Pendant",
    categorySlug: "diamond",
    price: 45999,
    salePrice: null,
    images: ["/images/collection-diamond.png"],
    tags: ["pendant", "diamond"],
    material: "Gold",
    goldPurity: "18K",
    weight: 3.4,
    stoneType: "Diamond",
    diamondDetails: "0.28 ct total diamond weight",
    makingCharges: 3900,
    hallmark: "BIS Hallmarked",
    stockCount: 10,
    shortDescription: "A delicate diamond pendant for subtle sparkle.",
    description: "A fine diamond pendant designed for clean everyday elegance.",
    isFeatured: false,
    isNewArrival: false,
    isBestSeller: true,
    isTrending: false,
  },
  {
    sku: "DIAMOND-BRACELET-001",
    name: "Ariya Diamond Bracelet",
    categorySlug: "diamond",
    price: 98999,
    salePrice: 92999,
    images: ["/images/collection-diamond.png", "/images/diamond-earrings.png"],
    tags: ["bracelet", "diamond", "premium"],
    material: "Gold",
    goldPurity: "18K",
    weight: 8.7,
    stoneType: "Diamond",
    diamondDetails: "0.76 ct total diamond weight",
    makingCharges: 8200,
    hallmark: "BIS Hallmarked",
    stockCount: 4,
    shortDescription: "A premium diamond bracelet with refined brilliance.",
    description: "A sophisticated diamond bracelet made for evening wear and special occasions.",
    isFeatured: true,
    isNewArrival: false,
    isBestSeller: false,
    isTrending: true,
  },
  {
    sku: "SILVER-RING-001",
    name: "Tara Silver Ring",
    categorySlug: "silver",
    price: 4999,
    salePrice: 3999,
    images: ["/images/collection-silver.png"],
    tags: ["ring", "silver", "daily-wear"],
    material: "Silver",
    weight: 7.2,
    stockCount: 30,
    shortDescription: "A clean silver ring with a modern profile.",
    description: "A lightweight silver ring designed for daily stacking and gifting.",
    isFeatured: false,
    isNewArrival: true,
    isBestSeller: true,
    isTrending: true,
    variants: [
      { size: "12", weight: 7.1, color: "Silver" },
      { size: "15", weight: 7.4, color: "Silver" },
    ],
  },
  {
    sku: "SILVER-EARRINGS-001",
    name: "Meera Silver Hoops",
    categorySlug: "silver",
    price: 6499,
    salePrice: null,
    images: ["/images/collection-silver.png"],
    tags: ["earrings", "hoops", "silver"],
    material: "Silver",
    weight: 9.8,
    stockCount: 24,
    shortDescription: "Polished silver hoops with a comfortable fit.",
    description: "Modern silver hoops made for casual looks and office wear.",
    isFeatured: false,
    isNewArrival: false,
    isBestSeller: true,
    isTrending: false,
  },
  {
    sku: "SILVER-ANKLET-001",
    name: "Kiara Silver Anklet",
    categorySlug: "silver",
    price: 7999,
    salePrice: 6799,
    images: ["/images/collection-silver.png"],
    tags: ["anklet", "silver", "gift"],
    material: "Silver",
    weight: 16.2,
    stockCount: 18,
    shortDescription: "A graceful silver anklet with small charm details.",
    description: "A polished silver anklet with an easy clasp and elegant charm accents.",
    isFeatured: true,
    isNewArrival: true,
    isBestSeller: false,
    isTrending: true,
  },
  {
    sku: "BRIDAL-CHOKER-001",
    name: "Aadhya Bridal Choker",
    categorySlug: "bridal",
    price: 159999,
    salePrice: 149999,
    images: ["/images/collection-bridal.png", "/images/bridal-banner.png"],
    tags: ["bridal", "choker", "kundan"],
    material: "Gold",
    goldPurity: "22K",
    weight: 38.5,
    stoneType: "Kundan",
    makingCharges: 15400,
    hallmark: "BIS Hallmarked",
    stockCount: 3,
    shortDescription: "A detailed bridal choker for statement wedding styling.",
    description: "A handcrafted bridal choker with kundan-inspired detailing and a regal silhouette.",
    isFeatured: true,
    isNewArrival: true,
    isBestSeller: false,
    isTrending: true,
  },
  {
    sku: "BRIDAL-NECKLACE-001",
    name: "Mihika Bridal Necklace",
    categorySlug: "bridal",
    price: 189999,
    salePrice: null,
    images: ["/images/bridal-banner.png", "/images/collection-bridal.png"],
    tags: ["bridal", "necklace", "premium"],
    material: "Gold",
    goldPurity: "22K",
    weight: 44.2,
    stoneType: "Polki",
    makingCharges: 18200,
    hallmark: "BIS Hallmarked",
    stockCount: 2,
    shortDescription: "A premium bridal necklace with a rich traditional form.",
    description: "A wedding necklace crafted for bridal portraits, ceremonies, and heirloom styling.",
    isFeatured: true,
    isNewArrival: false,
    isBestSeller: true,
    isTrending: true,
  },
  {
    sku: "BRIDAL-EARRINGS-001",
    name: "Zoya Bridal Jhumkas",
    categorySlug: "bridal",
    price: 79999,
    salePrice: 73999,
    images: ["/images/collection-bridal.png"],
    tags: ["bridal", "jhumka", "earrings"],
    material: "Gold",
    goldPurity: "22K",
    weight: 18.4,
    stoneType: "Kundan",
    makingCharges: 7600,
    hallmark: "BIS Hallmarked",
    stockCount: 6,
    shortDescription: "Bridal jhumkas with a graceful traditional drop.",
    description: "Statement jhumka earrings designed to pair beautifully with bridal sets.",
    isFeatured: false,
    isNewArrival: true,
    isBestSeller: true,
    isTrending: false,
  },
];

async function upsertCategory(category: (typeof sampleCategories)[number]) {
  const existing = await Category.findOne({ slug: category.slug });

  if (existing) {
    existing.set(category);
    return existing.save();
  }

  return Category.create(category);
}

async function upsertProduct(product: (typeof sampleProducts)[number], categoryId: number) {
  const { categorySlug: _categorySlug, ...productFields } = product;
  const existing = await Product.findOne({ sku: product.sku });

  if (existing) {
    existing.set({ ...productFields, categoryId });
    return existing.save();
  }

  return Product.create({ ...productFields, categoryId });
}

export async function seedDefaults() {
  await Coupon.updateOne(
    { code: "WELCOME10" },
    {
      code: "WELCOME10",
      type: "percentage",
      value: 10,
      minOrderTotal: 1000,
      active: true,
    },
    { upsert: true },
  );

  const categories = await Promise.all(sampleCategories.map(upsertCategory));
  const categoryBySlug = new Map(categories.map((category) => [category.slug, category.id]));

  await Promise.all(
    sampleProducts.map((product) => {
      const categoryId = categoryBySlug.get(product.categorySlug);
      if (categoryId == null) {
        throw new Error(`Missing seeded category for ${product.categorySlug}`);
      }

      return upsertProduct(product, categoryId);
    }),
  );
}
